import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootHeader from "./(Components)/RootHeader";
import RootFooter from "./(Components)/RootFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          {/* HEADER */}
          <RootHeader />
          {/* MAIN CONTENT */}
          <main className="flex-1 max-w-7xl w-full mx-auto px-4 py-6">
            {children}
          </main>

          {/* FOOTER */}
          <RootFooter />
        </div>
      </body>
    </html>
  );
}
